GET http://localhost:8000/api

###

POST http://localhost:8000/api/login

###

POST http://localhost:8000/api/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImF1Z3VzdGJhdGNoIiwiZW1haWwiOiJhdWcyMUBnbWFpbC5jb20ifSwiaWF0IjoxNjUxODQ2NjQ1LCJleHAiOjE2NTE4NDY3MDV9.uTEMoUZIkA5gOs07U46J4ucOnAI8Wjwi2DW0lQUewKk